import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-10 flex gap-10">
        <Link href="/">Home</Link>
        <Link href="/client">Client Example</Link>
        <Link href="/serveronly">Server Example</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
